// Export pages
export 'signin/signin_widget.dart' show SigninWidget;
export 'otppage/otppage_widget.dart' show OtppageWidget;
export 'signup/signup_widget.dart' show SignupWidget;
export 'home/home_widget.dart' show HomeWidget;
export 'findproduct/findproduct_widget.dart' show FindproductWidget;
export 'orderhistory/orderhistory_widget.dart' show OrderhistoryWidget;
export 'cart/cart_widget.dart' show CartWidget;
export 'home1/home1_widget.dart' show Home1Widget;
export 'paymentmethod/paymentmethod_widget.dart' show PaymentmethodWidget;
export 'orderhistory2/orderhistory2_widget.dart' show Orderhistory2Widget;
export 'test/test_widget.dart' show TestWidget;
export 'category/category_widget.dart' show CategoryWidget;
export 'favorite/favorite_widget.dart' show FavoriteWidget;
export 'test4/test4_widget.dart' show Test4Widget;
export 'product/product_widget.dart' show ProductWidget;
export 'cart1/cart1_widget.dart' show Cart1Widget;
export 'profile/profile_widget.dart' show ProfileWidget;
export 'edit_profile/edit_profile_widget.dart' show EditProfileWidget;
